name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Rust ${{ matrix.displayName }} ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
        rust: [nightly]
        include:
          - os: macos-10.15
            displayName: macOS
          - os: ubuntu-20.04
            displayName: Ubuntu
          - os: windows-2019
            displayName: Windows

    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.rust }} rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - run: cargo -Vv && rustc -Vv
      - run: cargo check
      - run: cargo check --all-features
        if: ${{ matrix.rust == 'stable' }}
      - run: cargo fmt --all -- --check
        if: ${{ matrix.rust == 'stable' }}
      - run: cargo test
        if: ${{ matrix.rust == 'stable' }}
