name: format

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - name: Cache Rust
        uses: Swatinem/rust-cache@v1

      - name: Format code with rustfmt
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
