name: Windows build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Rust Windows ${{ matrix.rust }}
    runs-on: windows-2019
    strategy:
      matrix:
        rust: [nightly]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install minimal ${{ matrix.rust }} rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ matrix.rust }}

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Check local package
        run: cargo check --bin voila

      - name: Run tests
        run: cargo test --bin voila
