name: Windows build

on:
  push:
    branches: [main]
    paths:
      - "/src"
  pull_request:
    branches: [main]
    paths:
      - "/src"

jobs:
  check:
    name: Rust Windows ${{ matrix.rust }}
    runs-on: windows-latest
    strategy:
      matrix:
        rust: [nightly]
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal ${{ matrix.rust }} rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - run: cargo -Vv && rustc -Vv
      - run: cargo check
      - run: cargo check --all-features
        if: ${{ matrix.rust == 'stable' }}
      - run: cargo fmt --all -- --check
        if: ${{ matrix.rust == 'stable' }}
      - run: cargo test
        if: ${{ matrix.rust == 'stable' }}
